=== TianJianJun0727/ycloud-lucide-icons/icon.schema.json
{
  "$id": "https://tianjianjun0727.github.io/ycloud-icons/icons.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },
  "title": "YCloud Icons icon schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["$schema", "contributors", "categories", "tags", "use-cases"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string"
          },
          "deprecated": {
            "const": true
          },
          "deprecationReason": {
            "$ref": "#/$defs/aliasDeprecationReasons"
          },
          "toBeRemovedInVersion": {
            "$ref": "#/$defs/versionNumber",
            "description": "The version this icon will be removed in."
          }
        },
        "dependentRequired": {
          "deprecated": ["deprecationReason", "toBeRemovedInVersion"],
          "deprecationReason": ["deprecated"],
          "toBeRemovedInVersion": ["deprecated"]
        }
      },
      "uniqueItems": true
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "accessibility",
          "account",
          "animals",
          "arrows",
          "buildings",
          "charts",
          "communication",
          "connectivity",
          "cursors",
          "design",
          "development",
          "devices",
          "emoji",
          "files",
          "finance",
          "food-beverage",
          "gaming",
          "home",
          "layout",
          "mail",
          "math",
          "medical",
          "multimedia",
          "nature",
          "navigation",
          "notifications",
          "people",
          "photography",
          "science",
          "seasons",
          "security",
          "shapes",
          "shopping",
          "social",
          "sports",
          "sustainability",
          "text",
          "time",
          "tools",
          "transportation",
          "travel",
          "weather"
        ]
      },
      "uniqueItems": true
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "i18n": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "zh": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "uniqueItems": true
            },
            "categories": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "uniqueItems": true
            }
          }
        }
      }
    },
    "use-cases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "deprecated": {
      "const": true
    },
    "deprecationReason": {
      "$ref": "#/$defs/iconDeprecationReasons"
    },
    "toBeRemovedInVersion": {
      "$ref": "#/$defs/versionNumber",
      "description": "The version this icon will be removed in."
    }
  },
  "dependentRequired": {
    "deprecated": ["deprecationReason", "toBeRemovedInVersion"],
    "deprecationReason": ["deprecated"],
    "toBeRemovedInVersion": ["deprecated"]
  },
  "$defs": {
    "iconDeprecationReasons": {
      "type": "string",
      "enum": ["icon.renamed"]
    },
    "aliasDeprecationReasons": {
      "type": "string",
      "enum": ["alias.typo", "alias.name", "alias.duplicate"]
    },
    "versionNumber": {
      "type": "string",
      "pattern": "v[0-9]+(\\.[0-9]+)+"
    }
  },
  "description": "A JSON Schema for icons defined by YCloud Icons."
}

=== TianJianJun0727/ycloud-lucide-icons/icons/a-arrow-down.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "it-is-not",
    "jguddas",
    "danielbayley",
    "ericfennis"
  ],
  "use-cases": [],
  "tags": [
    "letter",
    "font size",
    "text",
    "formatting",
    "smaller"
  ],
  "categories": [
    "text",
    "design"
  ],
  "i18n": {
    "zh": {
      "name": "字号减小",
      "tags": [
        "字母",
        "字号",
        "文本",
        "格式",
        "更小"
      ],
      "categories": [
        "文本格式",
        "设计"
      ]
    }
  }
}
